// Packages
export const FETCH_PACKAGES = 'FETCH_PACKAGES';
export const CREATE_PACKAGE = 'CREATE_PACKAGE';
export const UPDATE_PACKAGE = 'UPDATE_PACKAGE';
export const DELETE_PACKAGE = 'DELETE_PACKAGE';
export const SET_CURRENT_PACKAGE = 'SET_CURRENT_PACKAGE'; // Add this line

// Bars
export const FETCH_BARS = 'FETCH_BARS';
export const CREATE_BAR = 'CREATE_BAR';
export const UPDATE_BAR = 'UPDATE_BAR';
export const DELETE_BAR = 'DELETE_BAR';
export const SET_BAR_NAME='SET_BAR_NAME';
export const FETCH_BAR_PACKAGES = 'FETCH_BAR_PACKAGES'; // Action type for fetching bar packages
export const SET_CURRENT_BAR = 'SET_CURRENT_BAR'; // Action type for setting the current bar

// LiveGames
// actionTypes.js
export const FETCH_LIVEGAMES = 'FETCH_LIVEGAMES';
export const CREATE_LIVEGAME = 'CREATE_LIVEGAME';
export const UPDATE_LIVEGAME = 'UPDATE_LIVEGAME';
export const DELETE_LIVEGAME = 'DELETE_LIVEGAME';

// Add new action types
export const SET_GAME_TYPE = 'SET_GAME_TYPE';
export const SET_WAITER_APPROVE = 'SET_WAITER_APPROVE';
export const SET_BAR = 'SET_BAR';
export const SET_TABLE_NAME = 'SET_TABLE_NAME';
export const SET_TABLE_NUMBER = 'SET_TABLE_NUMBER';
export const SET_PACKAGE = 'SET_PACKAGE';
export const SET_PLAYERS_NAMES = 'SET_PLAYERS_NAMES';
export const SET_CURRENT_GAME_ID = 'SET_CURRENT_GAME_ID';
export const UPDATE_APPROVAL_FAILURE = 'UPDATE_APPROVAL_FAILURE';
export const UPDATE_APPROVAL_SUCCESS = 'UPDATE_APPROVAL_SUCCESS';
export const UPDATE_LIVEGAME_FAILURE = 'UPDATE_LIVEGAME_FAILURE';
export const DELETE_LIVE_GAMES = 'DELETE_LIVE_GAMES';
export const DELETE_LIVE_GAMES_SUCCESS = 'DELETE_LIVE_GAMES_SUCCESS';
export const DELETE_LIVE_GAMES_FAILURE = 'DELETE_LIVE_GAMES_FAILURE';



//questions
export const FETCH_QUESTIONS_SUCCESS = 'FETCH_QUESTIONS_SUCCESS';
export const FETCH_CATEGORY_QUESTIONS_SUCCESS = 'FETCH_CATEGORY_QUESTIONS_SUCCESS';
export const FETCH_GAME_QUESTIONS_SUCCESS = 'FETCH_GAME_QUESTIONS_SUCCESS';
export const ADD_QUESTION_SUCCESS = 'ADD_QUESTION_SUCCESS';
export const REMOVE_QUESTION_SUCCESS = 'REMOVE_QUESTION_SUCCESS';
export const UPDATE_DIFFICULTY_SUCCESS = 'UPDATE_DIFFICULTY_SUCCESS';
export const UPDATE_QUESTION_USE_SUCCESS = 'UPDATE_QUESTION_USE_SUCCESS';
export const UPDATE_QUESTION_RATE_SUCCESS = 'UPDATE_QUESTION_RATE_SUCCESS';
export const FETCH_DATE_QUESTIONS_SUCCESS='FETCH_DATE_QUESTIONS_SUCCESS';
export const FETCH_FRIENDS_QUESTIONS_SUCCESS='FETCH_FRIENDS_QUESTIONS_SUCCESS';
export const FETCH_GUESS_WHAT_I_AM_QUESTIONS_SUCCESS='FETCH_GUESS_WHAT_I_AM_QUESTIONS_SUCCESS';

// Additional action types (if needed)
export const SET_ERROR = 'SET_ERROR'; // Action type for setting errors
// src/store/actionTypes.js
export const SET_LOADING = 'SET_LOADING';

